## how to not get hung up on errors
def spam(divideBy):
    try:
        return 42 / divideBy
    except ZeroDivisionError:
        print('Error: Invalid argument.')
        
print(spam(2))
print(spam(12))
print(spam(0)) #without the try-except formulation, this would crash and not move on to the next line
print(spam(1))

def spam(divideBy):
    return 42 / divideBy
## if you do the above, it'll run all of the spam values, but it'll throw an error for spam(0)

## if you do the below, it'll stop at the error at spam(0) and never move on to spam(1)
try:
    print(spam(2))
    print(spam(12))
    print(spam(0))
    print(spam(1))
except ZeroDivisionError:
    print('Error: Invalid argument.')
